version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment :
    - DB_HOST=db
    - DB_DATABASE=db
    - DB_USERNAME=user
    - DB_PASSWORD=admin
    depends_on:
    - db
  db:
   image: mysql:
   environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=db
    - MYSQL_USER=user
    - MYSQL_PASSWORD=admin
